app:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    transactions-topic: ${KAFKA_TRANSACTIONS_TOPIC:mortgage.account.transactions}
    rules-topic: ${KAFKA_RULES_TOPIC:mortgage.loan.rules}
    group-id: ${KAFKA_GROUP_ID:flink-loan-eligibility-group}
    security-protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    sasl-mechanism: ${KAFKA_SASL_MECHANISM:}
    sasl-jaas-config: ${KAFKA_SASL_JAAS_CONFIG:}

  postgres:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/loan_db}
    username: ${POSTGRES_USERNAME:flink}
    password: ${POSTGRES_PASSWORD:flink}
    table-name: ${POSTGRES_TABLE:loan_eligibility}

  rules:
    threshold-amount: ${RULE_THRESHOLD_AMOUNT:500.0}
    currency: ${RULE_CURRENCY:GBP}
    required-transaction-status: ${RULE_REQUIRED_TRANSACTION_STATUS:APPROVED}
    required-account-status: ${RULE_REQUIRED_ACCOUNT_STATUS:ACTIVE}
    loan-rule-version: ${LOAN_RULE_VERSION:v1}